name: Run Cypress&Jest when PR on Main branch
on:
  pull_request:
    branches:
      - main
jobs:
  setup:
    runs-on: RedBankMac

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
 
    - name: Server/Node/ [Check Installation]
      run: node --version || echo 'Node.js is not installed'
      id: check_node_installed
      continue-on-error: true

    - name: Serve/Node/ [Install Node.js and npm]
      if : steps.check_node_installed.outcome == 'failure'
      uses: actions/setup-node@v2
      with:
          node-version: '21'
    
    - name: Server/npm [npm install]
      run: npm install
      working-directory: server
  
    - name: Server/mongod [Check if mongod is running]
      run: ps aux | grep -v grep | grep mongod || echo 'mongod is not running'
      id: check_mongod_running
      continue-on-error: true
      
    - name: Server/ [Run Jest Test]
      run: npx jest --runInBand --coverage
      working-directory: server/

    - name: Client/npm [npm install]
      run: npm install 
      working-directory: client/

    - name: Client/ [cypress install]
      run: npm install cypress
      working-directory: client/

    - name: Mongo/ [Remove DB]
      run: node destroy.js
      working-directory: server/
      
    - name: Mongo/ [Populate DB]
      run: node init.js
      working-directory: server/
      
    - name: Start the node server
      run: node server.js > server.log 2>&1 &
      working-directory: server/ 
    
    - name: Start the Client
      run: npm start &
      working-directory: client/
    
    - name: Run e2e tests
      run: npx cypress run --spec cypress/e2e/
      working-directory: client/
    
    - name: Run component tests
      run: npx cypress run --component
      working-directory: client/
    

          
